### ISSUE TITLE
Please add the topic team-opdrachten for dependabot-security-alerts support

### ISSUE THREAD

**Issue by barrydaniels-nl** [Amsterdam/iiif-auth-proxy#156]
Dependabot-security-alerts via slack require a team name. The team name must have the format team-{TEAMNAME}. 
Please add a topic team-opdrachten to this repository.

**Comment by TerryvanWalen** [comment]
I have added it to the about section. Is it now set correctly? We already had opdrachtenteam before. Should we keep that or remove it?

**Comment by barrydaniels-nl** [comment]
This should work now. You can remove the old opdrachtenteam if it is not used by anyone else.
